[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "FreeTSE"
version = "0.1.0"
authors = [
  { name="Toru Seo", email="toruseo@gmail.com" },
]
description = "A package for Free Traffic Simulation Environment"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas",
    "matplotlib",
    "numpy",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["FreeTSE*"]
exclude = ["tests*"]

[tool.setuptools.package-data]
"FreeTSE" = ["dat/*.csv", "dat/*.ini"]
